AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal AWS SAM template for local development.

Globals:
  Function:
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'http://localhost:3000'"
      AllowCredentials: true


Resources:
  ClaudeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        Api:
          Type: Api
          Properties:
            Path: /claude
            Method: GET
